config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "apps#about"
  resources :apps do
    resource :comments, only: :create 
    resource :likes, only: [:create, :destroy] 
    collection do
      get 'about'
      get 'search'
    end
  end
  resources :users, only: [:edit, :update]
end

app/models/app.rb
class App < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  validates :image, presence: true
  validates :name, presence: true
  validates :content, presence: true
  validates :genre_id, numericality: { other_than: 1, message: "can't be blank" }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name genre_id]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :app

  validates :content, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ARゲーム' },
    { id: 3, name: 'アクション' },
    { id: 4, name: 'アドベンチャー' },
    { id: 5, name: 'インディーズ' },
    { id: 6, name: 'カード' },
    { id: 7, name: 'カジノ' },
    { id: 8, name: 'カジュアル' },
    { id: 9, name: 'シミュレーション' },
    { id: 10, name: 'ストラテジー' },
    { id: 11, name: 'スポーツ' },
    { id: 12, name: 'トリビア' },
    { id: 13, name: 'パズル' },
    { id: 14, name: 'ファミリー' },
    { id: 15, name: 'ボード' },
    { id: 16, name: 'ミュージック' },
    { id: 17, name: 'レーシング' },
    { id: 18, name: 'ロールプレイング' },
    { id: 19, name: '子供向け' },
    { id: 20, name: '単語' }
  ]

  include ActiveHash::Associations
  has_many :apps
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :app
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :apps
  has_many :likes
  has_many :comments

  validates :name, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'Include both letters and numbers' }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :authenticate_user!, except: [:about]
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  def index
    @apps = App.all.order('created_at DESC')
  end

  def about
  end

  def new
    @app = App.new
  end

  def create
    @app = App.new(app_params)
    if @app.valid?
      @app.save
      redirect_to apps_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comments = @app.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    if current_user.id == @app.user.id
      render :edit
    else
      redirect_to apps_path
    end
  end

  def update
    if @app.update(app_params)
      redirect_to app_path(@app.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    return unless user_signed_in? && current_user.id == @app.user.id

    @app.destroy
    redirect_to apps_path
  end

  def search
    @q = App.ransack(params[:q])
    @apps = @q.result
  end

  private

  def app_params
    params.require(:app).permit(:image, :name, :content, :genre_id).merge(user_id: current_user.id)
  end

  def set_app
    @app = App.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @app = App.find(params[:app_id])
    return unless @comment.save

    CommentChannel.broadcast_to @app, { comment: @comment, user: @comment.user }
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, app_id: params[:app_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_app

  def create
    like = current_user.likes.build(app_id: params[:app_id])
    like.save
    respond_to app_path(@app.id)
    # respond_to do |format|
    #   format.js
    # end
  end

  def destroy
    like = Like.find_by(app_id: params[:app_id], user_id: current_user.id)
    like.destroy
    respond_to app_path(@app.id)
    # respond_to do |format|
    #   format.js
    # end
  end

  def set_app
    @app = App.find(params[:app_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      redirect_to '/'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/about.html.erb
<%= render "shared/header" %>

<%# トップページ %>

<div class= 'main'>
  <div class= 'main-content'>
    <div class= 'main-name'>FavApp</div>
    <div class= 'main-right'>
      <div class= 'main-text'>
        <h1>おすすめのアプリを紹介しよう</h1>
        <p>いいねやコメント機能があるよ</p>
        <p>暇つぶしできるアプリが見つかるかも・・？</p>
      </div>
      <ul class= 'main-menu'>
      <% unless user_signed_in? %>
      <li><%= link_to '新規登録', new_user_registration_path, class: 'main-sign-btn' %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

<%# トップページ %>

<%= render "shared/footer" %>

app/views/apps/edit.html.erb
<%= render "shared/header" %>

<%# 投稿内容編集画面 %>

<div class ='new-main-post'>
  <h2 class= 'new-post-title'>投稿内容編集</h2>
  <%= form_with model:@app, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

<%# 投稿フォーム %>
    <%# アプリ名 %>
    <div class="new-apps">
      <%= f.text_area :name, class:"post-name", id:"item-name", placeholder:"アプリ名", maxlength:"40" %>
      <div class="apps-explain">
    </div>
    <%# おすすめポイント %>
    <div class="new-apps">
      <%= f.text_area :content, class:"post-text", id:"item-content", placeholder:"おすすめポイント", maxlength:"200" %>
      <div class="apps-explain">
    </div>
    <%# ジャンル %>
    <div class="new-apps">
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"app-genre"}) %>
      <div class="apps-explain">
    </div>
    <%# 画像 %>
    <div class="img-upload">
      <div class="click-upload">
        <p>
          お気に入りのシーンをアップロードしよう!
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "Update" ,class:"new-post-btn" %>
    </div>

  <% end %>
</div>

<%# 投稿内容編集画面 %>

app/views/apps/index.html.erb
<%= render "shared/header" %>

<%# 投稿一覧画面 %>

  <div class='posts-contents'>
  <div class='toumei'>
    <ul class='posts-lists'>
      <% @apps.each do |app| %>
      <li class='list sen'>
        <%= link_to app_path(app.id),class: 'list-link',data: { turbo: false } do %>
        <div class='post-img-content'>
          <%= image_tag app.image, class: "post-img" %>
        </div>
        <div class='post-info'>
          <h3 class='new-post-name'>
            <%= app.name %>
          </h3>
            <span><%= app.content %><br>
            <div class='post-contents-box'>
            <%= "#{Genre.find(app.genre_id).name}" %></span>
            <div class='star-btn'>
              <span class='star-count'>💗</span><%= app.likes.count %>
             </div>
             </div>
        </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  </div>
  </div>

  <%# 投稿一覧画面 %>

app/views/apps/new.html.erb
<%# おすすめアプリ投稿画面 %>

<div class ='new-main-post'>
<%= link_to image_tag("Favapp.png", class:"favapp-new-logo"), "/" %>
  <h2 class= 'new-post-title'>新規投稿</h2>
  <%= form_with model:@app, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

<%# 投稿フォーム %>
    <%# アプリ名 %>
    <div class="new-apps">
      <%= f.text_area :name, class:"post-name", id:"item-name", placeholder:"アプリ名", maxlength:"40" %>
      <div class="apps-explain">
    </div>
    <%# おすすめポイント %>
    <div class="new-apps">
      <%= f.text_area :content, class:"post-text", id:"item-content", placeholder:"おすすめポイント", maxlength:"200" %>
      <div class="apps-explain">
    </div>
    <%# ジャンル %>
    <div class="new-apps">
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"app-genre"}) %>
      <div class="apps-explain">
    </div>
    <%# 画像 %>
    <div class="img-upload">
      <div class="click-upload">
        <p>
          お気に入りのシーンをアップロードしよう!
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "Post" ,class:"new-post-btn" %>
    </div>

  <% end %>
</div>

<%# おすすめアプリ投稿画面 %>

app/views/apps/search.html.erb
<%# 検索画面 %>

<%= render "shared/header_search" %>

  <div class='posts-contents'>
  <div class='toumei'>


    <ul class='posts-lists'>
      <% @apps.each do |app| %>
      <li class='list sen'>
        <%= link_to app_path(app.id),class: 'list-link' do %>
        <div class='post-img-content'>
          <%= image_tag app.image, class: "post-img" %>
        </div>
        <div class='post-info'>
          <h3 class='new-post-name'>
            <%= app.name %>
          </h3>
            <span><%= app.content %><br>
            <div class='post-contents-box'>
            <%= "#{Genre.find(app.genre_id).name}" %></span>
            <div class='star-btn'>
              <span class='star-count'>💗</span><%= app.likes.count %>
             </div>
             </div>
        </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  </div>
  </div>

  <%# 検索画面 %>

app/views/apps/show.html.erb
<%= render "shared/header" %>

<%# 投稿概要 %>
<div class="post-show">
  <div class="post-box">
    <h2 class="name">
      <%= @app.name %>
    </h2>
    <div class="post-img-content">
      <%= image_tag @app.image ,class:"post-box-img" %>
    </div>
    
    <% if user_signed_in? %>
      <% if current_user.id == @app.user_id  %>
      <div class= 'show-btn'>
        <%= link_to "編集", edit_app_path, data: { turbo: false },class: "edit-post-btn" %>
        <%= link_to "削除", app_path(@app.id), data: { turbo_method: :delete }, class:"post-destroy" %>
      </div>
      <% end %>
    <% end %>

    <div class="post-explain-box">
      <span><%= @app.content %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-post">投稿者</th>
          <td class="detail-user"><%= @app.user.name %></td>
        </tr>
        <tr>
          <th class="detail-post">ジャンル</th>
          <td class="detail-user"><%= Genre.find(@app.genre_id).name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
          <div id="like-btn<%= @app.id %>">
            <%= render partial: "likes/like", locals: { app: @app } %>
          </div>
      </div>
    </div>
  </div>
  <%# 投稿概要 %>
  <%# コメント機能 %>
<div id="comments">
  <h4>＜コメント一覧＞</h4>
    <% @app.comments.each do |comment| %>
      <div class="comment">
        <p class="user-info"><%= comment.user.name %>： </p>
        <p><%= comment.content%></p>
      </div>
    <% end %>
</div>
  <div class="comment-form">
    <%= form_with model: [@app, @comment], data: { turbo: false }, url: app_comments_path(@app), id: "comment-form" do |f| %>
      <div class= 'comment-btn'>
        <%= f.text_area :content , class: "comment-text"%>
        <%= f.submit "send", class: "comment-submit" %>
      </div>
    <% end %>
  </div>
  <%# コメント機能 %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
    <%# いいねボタン変化 %>
    <% if app.liked_by?(current_user)%>
      <%=link_to "💗", app_likes_path(app.id), data: { turbo_method: :delete }, class: "app_likes float", remote: true %>
      <%= app.likes.count %>
    <% else %>
      <%=link_to "🤍", app_likes_path(app.id), data: { turbo_method: :post }, class: "app_likes float", remote: true %>
    <%= app.likes.count %>
    <% end %>
    <%# いいねボタン変化 %>

app/views/likes/退避/create.js.erb
document.getElementById('like-btn<%= @app.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {app: @app}) %>"

app/views/likes/退避/destroy.js.erb
document.getElementById('like-btn<%= @app.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {app: @app}) %>"

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class= 'footer'>
  <div class='footer-contents'>©︎Momota</div>
</footer>

app/views/shared/_header.html.erb
  <%# CSS・・・assets/stylesheets/shared/header.css %>
<header class= 'top-page-header'>

  <ul class= 'header-btn'>
    <%= link_to image_tag("Favapp.png", class:"favapp-logo"), "/" %>
    <% if user_signed_in? %>
    <li><%= link_to current_user.name, edit_user_path(current_user), class: 'header-name' %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, class: 'header-logout', data: { turbo_method: :delete } %></li>
    <li><%= link_to 'おすすめアプリ投稿', new_app_path, class: 'main-post' %></li>
    <li><%= link_to '投稿一覧', apps_path, class: 'main-posts' %></li>
    <li><%= link_to '検索', search_apps_path, class: 'main-search' %></li>
    <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: 'header-login' %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: 'header-signup' %></li>
    <% end %>
  </ul>


</header>

app/views/shared/_header_search.html.erb
  <%# CSS・・・assets/stylesheets/shared/header.css %>
<header class= 'top-page-header'>

  <ul class= 'header-btn'>
    <%= link_to image_tag("Favapp.png", class:"favapp-logo"), "/" %>
    <% if user_signed_in? %>
    <li><%= link_to current_user.name, edit_user_path(current_user), class: 'header-name' %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, class: 'header-logout', data: { turbo_method: :delete } %></li>
    <li><%= link_to 'おすすめアプリ投稿', new_app_path, class: 'main-post' %></li>
    <li><%= link_to '投稿一覧', apps_path, class: 'main-posts' %></li>
    <li><%= link_to '検索', search_apps_path, class: 'main-search' %></li>
    <%= search_form_for @q, url:search_apps_path,html: {id: "detailed-search-form"} do |f| %>
    <div class='header-search'>
    <%# <div class="search-field"> %>
    <%# <div class='search-app-name'> %>
    <%# <%= f.text_field :name_cont, placeholder: 'アプリ名' %>
    <%# </div> %>
    <%# <div class='search-submit'> %>
    <%# <%= f.submit 'Search', class: 'search-submit-btn',id: 'search-submit-name' %>
    <%# </div> %>
    <%# </div> %>
    <div class="search-field">
    <div class='search-app-name'>
    <%= f.collection_select(:genre_id_eq, Genre.all, :id, :name) %>
    </div>
    <div class='search-submit'>
    <%= f.submit 'Search', class: 'search-submit-btn',id: 'search-submit-genre' %>
    </div>
    </div>
    </div>
  <% end %>
    <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: 'header-login' %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: 'header-signup' %></li>
    <% end %>
  </ul>


</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("Favapp.png", class:"favapp-icon"), "/" %>
</header>

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: current_user, class: 'registration-main', local: true do |f| %>
<div class= 'form-wrap'>
  <div class= 'form-header'>
    <h1 class= 'form-header-text'> ユーザー情報編集 </h1>
  </div>

    <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
    </div>
    <%= f.text_area :name, class:"input-default", id:"name",  maxlength:"30" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='register-btn'>
      <%= f.submit "Update" ,class:"register-signup-btn" %>
    </div>
  </div>
</div>
<% end %>

<%= render "shared/footer" %>